/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Akari Day tokens (Canonical Washi & Akari Paper palette)
        light: {
          canvas: '#EAE0CE',
          surface: '#FAF6EE',
          'surface-raised': '#FFFFFF',
          'surface-muted': '#E4D8C3',
          'surface-card': '#FAF6EE',
          ink: '#282E3A',
          'ink-muted': '#686559',
          'ink-subtle': '#8B8375',
          border: '#D4C4AA',
          'border-channel': 'transparent',
          'border-inner': 'transparent',
          'border-strong': '#BDAB8F',
          'button-dark': '#26262E',
          'on-dark': '#FAF6EE',
          accent: '#B5482E',
        },
        // Dark Palette (Sumi & Charred Cedar: Canvas #121316, Card Surface #23262F, Text #E8E6DF, Border #383B44, Accent Gold #D4A853)
        dark: {
          canvas: '#121316',
          panel: '#23262F',
          surface: '#23262F',
          card: '#23262F',
          'surface-card': '#23262F',
          'surface-raised': '#2C303B',
          'surface-muted': '#0E0F12',
          ink: '#E8E6DF',
          'ink-muted': '#9E9A8E',
          'ink-subtle': '#736F64',
          border: '#383B44',
          'border-channel': '#18191E',
          'border-inner': '#2E313A',
          'border-strong': '#4E5362',
          'button-light': '#D4A853',
          'on-light': '#121316',
          accent: '#D4A853',
        },
        // Brand & Accent tokens
        terracotta: {
          DEFAULT: '#B5482E',
          hover: '#9E3D27',
          soft: '#F0D7C7',
          glow: 'rgba(181, 72, 46, 0.2)',
        },
        bamboo: {
          DEFAULT: '#526D57',
          light: '#658B7B',
          dark: '#2D4D40',
        },
        ochre: {
          DEFAULT: '#D4A853',
          light: '#E6BE75',
          dark: '#C49A4A',
          hover: '#DE9E36',
          soft: '#F5E6CA',
        },
      },
      fontFamily: {
        serif: ['var(--font-display)', 'Zen Old Mincho', 'Noto Serif JP', 'Georgia', 'serif'],
        sans: ['var(--font-body)', 'Mulish', 'Plus Jakarta Sans', 'DM Sans', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'Azeret Mono', 'JetBrains Mono', 'Space Mono', 'IBM Plex Mono', 'monospace'],
        vertical: ['var(--font-vertical)', 'Zen Old Mincho', 'Noto Serif JP', 'serif'],
        display: ['var(--font-display)', 'Zen Old Mincho', 'Syne', 'Unbounded', 'Bricolage Grotesque', 'serif'],
        chamfer: ['var(--font-accent)', 'Chakra Petch', 'Space Grotesk', 'sans-serif'],
        chakra: ['var(--font-accent)', 'Chakra Petch', 'Space Grotesk', 'sans-serif'],
        zen: ['var(--font-display)', 'Zen Old Mincho', 'Noto Serif JP', 'serif'],
        mulish: ['var(--font-body)', 'Mulish', 'sans-serif'],
        azeret: ['var(--font-mono)', 'Azeret Mono', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        'display-lg': ['4rem', { lineHeight: '1.08' }],
      },
      spacing: {
        gutter: '1.5rem',
        'space-xs': '0.375rem',
        'space-sm': '0.75rem',
        'space-md': '1.25rem',
        'space-lg': '2rem',
        'space-xl': '3.5rem',
      },
      boxShadow: {
        akari: '0 4px 16px rgba(43, 46, 58, 0.04)',
        'akari-raised': '0 8px 24px rgba(43, 46, 58, 0.08)',
        'night-glow': '0 8px 24px -4px rgba(0, 0, 0, 0.5)',
        'hanko-glow': '0 0 12px rgba(181, 72, 46, 0.35)',
      },
      // Deliberate Border Radii: 0px to 3px for architectural structure & stationery craft
      borderRadius: {
        none: '0px',
        xs: '2px',
        sm: '2px',
        md: '3px',
        lg: '3px',
        xl: '3px',
        '2xl': '3px',
        '3xl': '3px',
        pill: '3px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
